### ISSUE TITLE
CUBLAS_STATUS_NOT_SUPPORTED in PyTorch 2.3 

### ISSUE THREAD

**Issue by NeroBlackstone** [EleutherAI/aria-amt#40]
Env: Python 3.11, Linux 6.9.1-arch1-1, GTX 970, Driver Version: 550.78, CUDA Version 12.5 with CUDNN.

```
myenv] ~/Documents/github/aria-amt> aria-amt transcribe medium-stacked ./piano-medium-stacked-1.0.safetensors -load_path ./ashs.mp3 -save_dir ./ -bs 1
[2024-06-02 18:05:17,890] 3985: [INFO] Files to process: 1/1
[2024-06-02 18:05:17,891] 3985: [INFO] Creating 1 file worker(s)
[2024-06-02 18:05:20,352] [B] 4015: [INFO] Started batch manager
[2024-06-02 18:05:20,391] [F] 4014: [INFO] Getting wav segments: ./ashs.mp3
[2024-06-02 18:05:22,893] [GPU] 3985: [INFO] Started GPU manager
[2024-06-02 18:05:24,267] [GPU] 3985: [ERROR] Failed to process batch: Traceback (most recent call last):
  File "/home/nero/Documents/github/aria-amt/amt/inference/transcribe.py", line 306, in gpu_manager
    results = process_segments(
              ^^^^^^^^^^^^^^^^^
  File "/home/nero/Documents/github/aria-amt/amt/inference/transcribe.py", line 136, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/nero/miniconda3/envs/myenv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/nero/Documents/github/aria-amt/amt/inference/transcribe.py", line 175, in process_segments
    audio_features = model.encoder(xa=log_mels)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nero/miniconda3/envs/myenv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nero/miniconda3/envs/myenv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nero/Documents/github/aria-amt/amt/inference/model.py", line 341, in forward
    xa = block(xa)
         ^^^^^^^^^
  File "/home/nero/miniconda3/envs/myenv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nero/miniconda3/envs/myenv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nero/Documents/github/aria-amt/amt/inference/model.py", line 267, in forward
    xa = xa + self.attn(
              ^^^^^^^^^^
  File "/home/nero/miniconda3/envs/myenv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nero/miniconda3/envs/myenv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nero/Documents/github/aria-amt/amt/inference/model.py", line 108, in forward
    wv = F.scaled_dot_product_attention(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasGemmStridedBatchedEx(handle, opa, opb, (int)m, (int)n, (int)k, (void*)&falpha, a, CUDA_R_16BF, (int)lda, stridea, b, CUDA_R_16BF, (int)ldb, strideb, (void*)&fbeta, c, CUDA_R_16BF, (int)ldc, stridec, (int)num_batches, compute_type, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`

[2024-06-02 18:05:24,267] [GPU] 3985: [ERROR] GPU manager failed with exception: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasGemmStridedBatchedEx(handle, opa, opb, (int)m, (int)n, (int)k, (void*)&falpha, a, CUDA_R_16BF, (int)lda, stridea, b, CUDA_R_16BF, (int)ldb, strideb, (void*)&fbeta, c, CUDA_R_16BF, (int)ldc, stridec, (int)num_batches, compute_type, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`
[2024-06-02 18:05:24,267] [GPU] 3985: [INFO] GPU manager terminated
Took 0.02400960922241211 mins to transcribe files
```

PyTorch 2.2 work as expected.

**Comment by NeroBlackstone** [comment]
I think this is a Torch bug?

**Comment by loubbrad** [comment]
I've encountered some issues with using the `-compile` flag on machines with older GPUs. Consider removing this flag if you have any torch related issues.
